#!python3

import sys

from ravestate.context import Context

ctx = Context(*sys.argv[1:])
ctx.run()

# TODO: Make sure that UI is cleanly integrated as a ravestate module.
# from ravestate_ui import service
# service.advertise(ctx=ctx)
